/**
 * Copies the web fonts the docs page needs out of node_modules and writes the
 * `@font-face` block that points at them.
 *
 * The page self-hosts rather than reaching for a font CDN: the container is
 * meant to be the whole of the deployment, and a docs page that renders with
 * no outbound network is part of that. Only the latin subsets are taken, which
 * is around 120 kB for the five faces.
 */
import { copyFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "site", "public", "assets", "fonts");
const CSS = join(ROOT, "site", "src", "styles", "fonts.css");

const FACES = [
  { pkg: "archivo", file: "archivo-latin-800-normal", family: "Archivo", weight: 800 },
  { pkg: "ibm-plex-sans", file: "ibm-plex-sans-latin-400-normal", family: "IBM Plex Sans", weight: 400 },
  { pkg: "ibm-plex-sans", file: "ibm-plex-sans-latin-500-normal", family: "IBM Plex Sans", weight: 500 },
  { pkg: "ibm-plex-sans", file: "ibm-plex-sans-latin-600-normal", family: "IBM Plex Sans", weight: 600 },
  { pkg: "ibm-plex-mono", file: "ibm-plex-mono-latin-400-normal", family: "IBM Plex Mono", weight: 400 },
  { pkg: "ibm-plex-mono", file: "ibm-plex-mono-latin-500-normal", family: "IBM Plex Mono", weight: 500 },
];

await mkdir(OUT, { recursive: true });

const rules = [];
for (const face of FACES) {
  const name = `${face.file}.woff2`;
  await copyFile(join(ROOT, "node_modules", "@fontsource", face.pkg, "files", name), join(OUT, name));
  rules.push(
    `@font-face {\n` +
      `  font-family: "${face.family}";\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${face.weight};\n` +
      `  font-display: swap;\n` +
      `  src: url("/assets/fonts/${name}") format("woff2");\n` +
      `}`,
  );
}

await writeFile(CSS, `/* Generated by scripts/fonts.mjs - do not edit. */\n${rules.join("\n\n")}\n`);

console.log(`fonts: ${FACES.length} faces into site/public/assets/fonts`);
